### PR TITLE
Clarify previousProof verification.

### PR DESCRIPTION
**Pull request by aljones15**
***
<a href="https://pr-preview.s3.amazonaws.com/aljones15/vc-data-integrity/pull/307.html" title="Last updated on Aug 30, 2024, 5:55 PM UTC (34335b8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-integrity/307/1d7bfa6...aljones15:34335b8.html" title="Last updated on Aug 30, 2024, 5:55 PM UTC (34335b8)">Diff</a>

### CODE REVIEW

**Review by dlongley — APPROVED** [review]

**Comment by PatStLouis** [comment]
@aljones15 @dlongley slightly related, in the `previousProof` data model section, I would like to suggest the following edit:

> ~~An OPTIONAL string value or unordered list of string values.~~  The `previousProof` property is OPTIONAL. If present, it MUST be a string value or unordered list of string values. Each value identifies another [data integrity proof](https://www.w3.org/TR/vc-data-integrity/#dfn-data-integrity-proof) that MUST verify before the current proof is processed. If an unordered list, all referenced proofs in the array MUST verify. This property is used in Section [2.1.2 Proof Chains](https://www.w3.org/TR/vc-data-integrity/#proof-chains).

Should I suggest this in a separate PR?

**Review by Wind4Greg — APPROVED** [review]

**Comment by dlongley** [comment]
@PatStLouis please either make the suggestion here (if the tools will let you) or, yes, open another PR.

**Comment by PatStLouis** [comment]
@aljones15 @dlongley #309

**Review by msporny — APPROVED** [review]

**Comment by msporny** [comment]
Editorial, multiple reviews, no changes requested, no objections, merging.

**Pull request merged**
