### PR TITLE
Merge with Linked Data Signatures spec

### PR DESCRIPTION
**Pull request by dmitrizagidulin**
This is a WIP pr that merges the [Linked Data Signatures](https://w3c-ccg.github.io/ld-signatures/) spec with this one.

Addresses issues https://github.com/w3c-ccg/ld-proofs/issues/5, #9, and https://github.com/w3c-ccg/ld-signatures/issues/29.

### CODE REVIEW

**Review by msporny — CHANGES_REQUESTED** [review]
The end result of this PR is good and is ready to be merged, but it doesn't maintain the history of the LD Signatures spec, which is important for IPR reasons.

**Comment by dmitrizagidulin** [comment]
@msporny agreed, yeah. Still working on that part.

**Comment by dmitrizagidulin** [comment]
@msporny the LD Signatures commit history has now been transferred into this PR.

**Review by msporny — APPROVED** [review]
LGTM, substantive, normative, multiple reviews, suggested changes made, merging.

**Comment by msporny** [comment]
Hmm, the rebase+merge destroyed the spec... can you look into what went wrong, @dmitrizagidulin? There is no Linked Data Signature content in the spec on gh-pages.

**Comment by msporny** [comment]
> Hmm, the rebase+merge destroyed the spec... can you look into what went wrong, @dmitrizagidulin? There is no Linked Data Signature content in the spec on gh-pages.

Actually, nevermind, the section was just somewhere I wasn't expecting it to be.

**Pull request merged**
