### PR TITLE
Remove myself from the editors list

### PR DESCRIPTION
**Pull request by mprorock**
Removing myself from the editors list for Data Integrity

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-integrity/pull/94.html" title="Last updated on Apr 25, 2023, 4:29 PM UTC (eca7b5d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-integrity/94/bf55970...eca7b5d.html" title="Last updated on Apr 25, 2023, 4:29 PM UTC (eca7b5d)">Diff</a>

### CODE REVIEW

**Review by msporny — APPROVED** [review]
:( - sorry to see you go, I'll start searching for a 2nd Editor.

**Review by dlongley — APPROVED** [review]

**Review by brentzundel — APPROVED** [review]

**Review by Sakurann — APPROVED** [review]

**Review by selfissued — APPROVED** [review]

**Review by iherman — APPROVED** [review]

**Review by iherman — APPROVED** [review]
@mprorock I presume that means you would also have to be removed from CODEOWNERS, right?

**Review by OR13 — APPROVED** [review]

**Comment by OR13** [comment]
@msporny I am happy to help edit, as long as you are ok arguing with me more :)

**Comment by msporny** [comment]
> @msporny I am happy to help edit, as long as you are ok arguing with me more :)

\**lol*\* I'm happy to keep arguing with you @OR13 if you're ok to keep arguing with me. Trial by fire is better than trial by silence. :)

Thanks for volunteering! 

We had another volunteer to be Editor on this spec from the RCH WG incoming (Sebastian Crane)... he'll have to join the WG as an IE (up to the discretion of the Chairs and Staff). He's been assigned as an Editor for the RDF Dataset Canonicalization spec, so will be a good overlap w/ that WG's work.

In any case, happy to add both @OR13 and @seabass-labrax as Editors.

**Pull request merged**
