### PR TITLE
Update of vocabulary files

### PR DESCRIPTION
**Pull request by iherman**
yml2vocab has now the ability of adding information on designated @context files that contain individual terms to the output. This change is adapted to this vocabulary.

Additionally, the vocabulary change takes care of #242 as well.

As usual, the automatic preview is useless for this case, see https://w3c.github.io/yml2vocab/previews/di/ for the new versions of the generated files.

### CODE REVIEW

**Review by msporny — CHANGES_REQUESTED** [review]
There seems to be a `.drawio.bkp` file erroneously checked in -- it should be removed before we merge this PR.

The rest of the changes look good. Thank you!

**Comment by iherman** [comment]
> There seems to be a `.drawio.bkp` file erroneously checked in -- it should be removed before we merge this PR.
> 

Damn. But this is as old error of mine: the .bkp file only appears in the main branch, not this one. Do you want me to create a separate PR with that removal, or would you simply remove it with a direct commit in main?

(I have, since then, modified my .gitignore file to avoid this.)

**Review by Wind4Greg — APPROVED** [review]

**Comment by msporny** [comment]
I removed the backup file on main and rebased this branch on top. That's fixed now, re-reviewing...

**Review by msporny — APPROVED** [review]

**Comment by msporny** [comment]
Editorial, multiple reviews, changes requested and made, no objections, merging.

**Pull request merged**
